### ISSUE TITLE
rename fibonacci-task to fibonacci-async-task

### ISSUE THREAD

**Issue by amilajack** [neon-bindings/examples#22]
This will help show that this is an async task. The links to this example must be changed in the docs as well

**Comment by kjvalencik** [comment]
:+1: This is also the only task example that shows how to get data to it. The others only use unit structs. This would help discovery.

Although, maybe it's helpful for the basic task example to show passing an argument as well?

**Comment by amilajack** [comment]
@kjvalencik totally agree!
