### ISSUE TITLE
how to return a buffer and how to set buffer content?

### ISSUE THREAD

**Issue by calidion** [neon-bindings/examples#43]
thanks.

**Comment by cisaacson** [comment]
I have an example to create and return a buffer that works. 

```
fn create_buffer(mut cx: FunctionContext) -> JsResult<JsBuffer> {
    let mut buffer = try!(JsBuffer::new(&mut cx, 16));
    cx.borrow_mut(&mut buffer, |data| {
        let slice = data.as_mut_slice::<u8>();
        for i in 0..slice.len() {
            slice[i] = (i + 1) as u8;
        }
    });

    Ok(buffer)
}
```

I still have not tried setting buffer content, will attempt that next.

**Comment by calidion** [comment]
@cisaacson 

thanks.

My project has now some examples too.

which you can checkout here:

1. send buffer

https://github.com/vigcoin/neon/blob/master/native/src/scalar.rs

https://github.com/vigcoin/neon/blob/c3f16712bba05276f51f0cb0129df2b58e4f8b16/native/src/signature.rs#L6

https://github.com/vigcoin/neon/blob/c3f16712bba05276f51f0cb0129df2b58e4f8b16/native/src/signature.rs#L37

2. receive buffer

https://github.com/vigcoin/neon/blob/c3f16712bba05276f51f0cb0129df2b58e4f8b16/native/src/hash.rs#L5

3. buffer array

https://github.com/vigcoin/neon/blob/c3f16712bba05276f51f0cb0129df2b58e4f8b16/native/src/signature.rs#L40

**Comment by cisaacson** [comment]
Great work, now I have what I need, thanks!
