### ISSUE TITLE
The electron example errors out

### ISSUE THREAD

**Issue by adityapk00** [neon-bindings/examples#46]
I just wanted to bring to your attention that the `electron-app` example doesn't work, and throws an exception. It has a couple of issues:

1. The npm package "hello-world" has been renamed to "neon-hello" on the npm repo
2. The "neon-hello" package is not updated on the npm repository (It doesn't match what's in the examples directory)
3. The `neon-cli` version in the `package.json` needs to be updated to `0.3.3` (from the current `0.3.1`), otherwise it fails with this error:

![image](https://user-images.githubusercontent.com/31996805/71610735-5c09b080-2b48-11ea-8eee-0c3228fb03c3.png)

**Comment by NetOpWibby** [comment]
Here in February 2020, this example still doesn't work.

```
error: failed to run custom build command for `neon-runtime v0.1.23`

Caused by:
  process didn't exit successfully: `/~/Downloads/examples-master/electron-app/node_modules/neon-hello/native/target/release/build/neon-runtime-03dcae148e2736ef/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
up to date in 0.928s

# stuff

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/~/Downloads/examples-master/electron-app/node_modules/neon-hello/native/target/release/build/neon-runtime-2f7929a2bc05ccb8/out/libneon.a" "build/Release/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).

', /~/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/~/Downloads/examples-master/electron-app/node_modules/neon-hello/node_modules/neon-cli/lib/target.js:124:35)
    at step (/~/Downloads/examples-master/electron-app/node_modules/neon-hello/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/~/Downloads/examples-master/electron-app/node_modules/neon-hello/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/~/Downloads/examples-master/electron-app/node_modules/neon-hello/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by kjvalencik** [comment]
This example needs to be updated. Please try this https://github.com/neon-bindings/neon/tree/master/test/electron

**Comment by usagi** [comment]
Is it solved? 🎉 At least for me, I can build and run in expectedly just now!

Screenshot of Windows:

![image](https://user-images.githubusercontent.com/115972/77258383-9608cf80-6cbd-11ea-9d82-c1961c0605c3.png)

Screenshot of Arch Linux(WSL2):

![image](https://user-images.githubusercontent.com/115972/77258644-4a572580-6cbf-11ea-8f6d-7e0c789391b3.png)

-----

But, it should be appear like the @adityapk00 's screenshot if you run `electron .` in the shell directly without `npm start` or `yarn start`.

**Comment by amilajack** [comment]
Users are expected to start the electron example with the `"start"` npm script
