### ISSUE TITLE
Can the Function persist ? 

### ISSUE THREAD

**Issue by xhsiung** [neon-bindings/examples#47]
how do i do ?

**Comment by kjvalencik** [comment]
Can you share a bit more about your use case? Functions exported on the module context will persist.

https://github.com/neon-bindings/examples/blob/master/hello-world/native/src/lib.rs

**Comment by xhsiung** [comment]
i want to call the thread another process in the Rust.
the process result emit  to  send  the Event in the Javascript.
how to do that ?

**Comment by kjvalencik** [comment]
Examples include using `JsBox` which can hold a `JsFunction`.
