### ISSUE TITLE
Fix the broken explains in `Setup` section of `README.md`

### ISSUE THREAD

**Issue by usagi** [neon-bindings/examples#50]
#### Problems:

1. [ ] The different directories
2. [ ] Is `undefined` the expected result?

Screenshot at the time of this reporting: 

![image](https://user-images.githubusercontent.com/115972/77255795-6a7de900-6cad-11ea-8470-2918530a76d7.png)

##### 1. The different directories

```sh
git clone https://github.com/neon-bindings/examples
cd neon-examples
```

Maybe, the expected fixing is append `neon-examples` to the tail of the first line. Then it will be work:

```sh
git clone https://github.com/neon-bindings/examples neon-examples
cd neon-examples
```

##### 2. Is `undefined` the expected result?

```sh
# Compile and run an example:
cd primitives
node ./lib/index.js
```

It will be returns `undefined` in Arch Linux(WSL 2) and Windows. At least, I gave up to use these examples for my studying NEON using this just as it is. I'll read the sources and debug first before run the example, it is very sadly situation for beginners. 😭

**Comment by usagi** [comment]
I could not understood these things at the first time of accessing this repos:

- Is `undefined` the expected result?:
    - It is yes maybe but user would not know the expected answer at the first time of try to this repos.
    - And, `undefined` will be return in failed to `require` situation in Node.js then user may not think "It is the expected behavor!". In commonly, the most of users think "What's happend? It's failed?", maybe.
    - Therefore, I think it is better idea that the example for this place of `README.md` change to the other example. Maybe, to use the `hello-world` is suitable for most users without no confusing.

-----
Of course, this might be a great training or implicit user filtering. But if so, I would be reconsider to use the project and contributing to this project. Be gentle for beginners and grow together. ❤️

**Comment by amilajack** [comment]
yes, `undefined` is the expected result. I agree that showing `undefined` can be confusing so I'll change the example. Thanks for the heads up!

**Comment by usagi** [comment]
Note: This issue to be simplify as the `cd` problem if the #53 merged. :tada:
