### ISSUE TITLE
Make it more understandable: primitives

### ISSUE THREAD

**Issue by usagi** [neon-bindings/examples#51]
`primitives` is not very kind for beginers who need the examples. This idea is to better more:

1. Split the `fn primitives` for each [JS primitive types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)
2. Call the all of splitted functions from `lib/index.js` with printing then it will be show 7 ( or 6 ) types/lines.
3. Append an useful link to the souce code commenting about [JS primitive types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) for helpful.

Workflow:

1. [x] Approval by the authors and colaborators
2. [x] Modifying
3. [x] PR & Merge

-----

related #50

**Comment by amilajack** [comment]
Would love if you can put together a PR for this! Unfortunately my attention is split between projects right now.

**Comment by usagi** [comment]
Yes, thank you to the opportunity for good exercise to me. I'll PR, you can assign to me for this issue. 

---
I kind of knew you are so good working with hard to this project side too because I'd saw your current status such "🔨 Busy working on Alfred (alfred.js.org)". I'm a newbie of NEON but you may not worry to my skill bases for Rust, ES/JS or C++.
